<?php
  session_start();
  if(!isset($_SESSION['user'])){
	header("location:login.php");
  }else{
	include('header.php');
	include('sidebar.php');
	include('main.php');
	include('footer.php');
  }
 ?>
